config/routes.rb
Placibo::Application.routes.draw do
  get "pages/home"
  
  resource :searches
  resources :inspiras do
    member {post :vote}
  end
end

app/models/inspira.rb
class Inspira < ActiveRecord::Base
  attr_accessible :message
  
  has_reputation :votes, source: :user, aggregated_by: :sum
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/inspiras_controller.rb
class InspirasController < ApplicationController
  def vote
    value = params[:type] == "up" ? 1: -1
    @inspira = Inspira.find(params[:id])
    @inspira.add_or_update_evaluation(:votes, value, session["user"])
    redirect_to :back, notice: "Thank you for voting"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    session["user"] = User.first
    @images = Dir.glob('public/images/background/*')
    @welcome_image = "/images/welcome_pic.jpeg"
    @create_image = "/images/create.png"
    @search_text = 'Search'
    @inspiras = Inspira.find_with_reputation(:votes, :all, order: "votes desc")
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def new
	text = "http://www.google.com/search?hl=en&btnI=I%27m+Feeling+Lucky&q="+ CGI::escape(params[:search])
	redirect_to text
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Placibo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
</body>
</html>

app/views/pages/home.html.erb
<div class="search" >
  <%= form_tag(new_searches_path, :method => "get", :class=>"form-inline")  do %>
    <%= text_field_tag :search , nil, placeholder: @search_text%>
    <%= link_to image_tag(@create_image), new_inspira_path, class: "btn pull-right" %>
  <% end %>
</div>
<div id="myCarousel" class="carousel slide">
  <div class="carousel-inner">
    <div class="active item">
  	  <img src= <%= @welcome_image %> alt="" class="pixastic pixastic-blur(amount=0.1)">
    </div>
    <% @images.each_with_index do |image, index| %>
      <% inspira = @inspiras[index] %>
      <div class="item">
  	    <img src= <%= image.sub("public","") %> alt="" class="pixastic pixastic-blur(amount=0.5)">
  	    <div class="inspira well transbox" style="top: <%=rand(0 .. 50)%>%; right: <%=rand(0 .. 60)%>%;"> 
  	      <p><%= inspira.message%></p>
  	      <%= pluralize inspira.reputation_value_for(:votes).to_i, "vote" %>
  	      |<%= link_to "up", vote_inspira_path(inspira, type: "up"), method: "post" %>
  	      |<%= link_to "down", vote_inspira_path(inspira, type: "down"), method: "post" %>
  	    </div>
      </div>
    <% end %>
  </div>
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">›</a>
</div>